calculator/urls.py
from django.urls import path

from . import views

app_name = 'calculator'
urlpatterns = [
    path('',views.HomePage.as_view(), name='homepage'),
    path('add_recipe/', views.HomePage.addItem, name = 'add_recipe'),
    path('<int:pk>/', views.RecipeDetailPage.as_view(),name='ing_list'),
    path('base/', views.BaseIngPage.as_view(), name='base_list'),
    path('base_delete/<int:id>/', views.BaseIngPage.as_view(), name='ing_delete'),
    path('recipeing_delete/<int:id>/', views.RecipeDetailPage.delete_ing, name='ring_delete'),
    path('recipe_delete/<int:id>/', views.HomePage.delete, name = 'recipe_delete'),
    path('search_recipe/', views.HomePage.search, name="recipe_search"),
    path('all_recieps/',views.RecipeFilterPage.as_view(), name="filterPage")
]

recipe_cal/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('calculator.urls')),
    path('admin/', admin.site.urls),
]

calculator/models.py
from django.db import models
import csv

class BaseIng(models.Model):
    ing_name = models.CharField(max_length=200)
    measurement_type = models.CharField(max_length=200)
    package_price = models.FloatField()
    package_size = models.FloatField()

    def __str__(self):
        return self.ing_name


    def readCSV(self, file):
        csv_reader = csv.reader(file)

        for line in csv_reader:
            print(line['FoodDescription'])

    def price_per_unit(self):
        return round(self.package_price/self.package_size, 3)

    



class Recipe(models.Model):
    recipe_name = models.CharField(max_length=200)
    servings = models.IntegerField()
    descripton = models.TextField()
    time_created = models.DateTimeField(auto_now_add=True)

    def parse_time(self):
        return self.time_created.strftime("%b. %d, %Y")

    def calulcate_price(self):
        total_price = 0
        servings_price = 0
        for ing in self.recipeing_set.all():
            total_price = total_price + ing.calulcate_price()

        final_price = total_price
        servings_price = total_price/self.servings
        return final_price, servings_price



    def __str__(self):
        return self.recipe_name

class RecipeIng(models.Model):
    item_mass = models.FloatField()
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    base_ing = models.ForeignKey(BaseIng, on_delete=models.CASCADE)
    
    def calulcate_price(self):
        return round(self.base_ing.price_per_unit()*self.item_mass, 2)

    def __str__(self):
        return self.base_ing.ing_name
    

calculator/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.utils import timezone
from django.template import loader
from django.shortcuts import render, get_object_or_404
from .models import *
from django.urls import reverse
from django.views import generic
from django.http import JsonResponse
from django.middleware.csrf import get_token
from django.template.context_processors import csrf
from django.views.decorators.csrf import requires_csrf_token
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.core import serializers
from django.db.models import Count



class HomePage(generic.ListView):

    template_name = 'calculator/homepage.html'
    context_object_name = 'recipe_list'


    def get_queryset(self):
    # recipe_list = recipe.objects.order_by('recipe_name')[:5]
    # output = ','.join([r.recipe_name for r in recipe_list])
        return Recipe.objects.order_by('recipe_name')[:5]

    def post(self, request):
        return HttpResponseRedirect(reverse("calculator:homepage"))
    
    @csrf_exempt
    def addItem(request):
        new_recipe = Recipe(recipe_name=request.POST.get('name'), servings=1, descripton=request.POST.get("desc"))
        new_recipe.save()

        data = {
            "id" : new_recipe.id,
            "url" : reverse("calculator:ing_list", kwargs={"pk" : new_recipe.id}),
            "del_url" : reverse("calculator:recipe_delete", kwargs={"id" : new_recipe.id}),
            "csrf" : get_token(request),
            "desc" : new_recipe.descripton,
            "time" : new_recipe.parse_time(),
        }

        return JsonResponse(data)

    
    @staticmethod
    def delete(request, id):
        recipe = get_object_or_404(Recipe, id=id)
        recipe.delete()

        return JsonResponse("Deleted",safe=False)

    @csrf_exempt
    @staticmethod
    def search(request):
        recipes = Recipe.objects.filter(recipe_name__contains=request.POST.get("name"))
        response = []
        for recipe in recipes:
            response.append({"label": recipe.recipe_name, 
            "value": recipe.id, "desc": recipe.descripton, 
            "date": recipe.parse_time(), 
            "del_url":reverse("calculator:recipe_delete", kwargs={"id" : recipe.id}),
            "url": reverse("calculator:ing_list", kwargs={"pk" : recipe.id})})
        return JsonResponse(response, safe=False)


@method_decorator(csrf_exempt, name='dispatch')
class RecipeFilterPage(generic.ListView):
    template_name = "calculator/recipe_filter.html"
    context_object_name = "recipe_list"

    def get_queryset(self):
        return Recipe.objects.order_by("-time_created")[:10]

    def filter(self, filter):
        pass
    
    def post(self, request):
        Date = ""
        Price = ""
        Name = ""

        if request.POST["Date"]=="Newest":
            Date = "time_created"
        if request.POST["Date"]=="Oldest":
            Date = "-time_created"
        
        if request.POST["Price"] == "Descending":
            Price = "-price"
        if request.POST["Price"] == "Ascending":
            Price = "price"

        if request.POST["Name"] == "Descending":
            Name = "-name"
        if request.POST["Name"] == "Ascending":
            Name = "name"

        filter = []

        for key, value in request.POST.items():
            col = ""
            if key=="Date":
                col = "time_created"
                if value == "Oldest":
                    col = "-" + col

            elif key=="Name":
                col = "recipe_name"
                if value == "Descending":
                    col = "-" + col

            if col != "":
                filter.append(col)


        
        
        recipes = Recipe.objects.order_by(*filter)
        if request.POST["minIng"] != "null":
            min = int(request.POST["minIng"])
            recipes = recipes.annotate(numIpytng=Count("recipeing"))
            recipes=recipes.filter(numIng__gte=min)
        


        SerializedObj = list(recipes.values())

        if request.POST["Price"] != "null":
            def key_func(x):
                price = Recipe.objects.get(pk=x["id"]).calulcate_price()[0]
                if request.POST["Price"] == "Ascending":
                    return price
                else:
                    return -price

            SerializedObj = sorted(SerializedObj, key=key_func)

        print(SerializedObj)
        for rec_id in SerializedObj:
            rec_id["url"] = reverse("calculator:ing_list", kwargs={"pk" : rec_id["id"]})


        return JsonResponse(SerializedObj,safe=False)
        
        
@method_decorator(csrf_exempt, name='dispatch')
class RecipeDetailPage(generic.DetailView):

    model = Recipe

    def post(self,request,*args,**kwargs):
        Bases = BaseIng
        if "servings" in request.POST:
            object = self.get_object()
            object.servings = int(request.POST.get('servings'))
            object.save()


            data = {
             "servings" : object.servings,
             "perSprice" : object.calulcate_price(),
            }

            return JsonResponse(data)

        else:
            newRecipeIng = RecipeIng(item_mass = float(request.POST.get('quan')), recipe=self.get_object(), base_ing=Bases.objects.get(id=request.POST.get('ing')))
            newRecipeIng.save()
            print(newRecipeIng.base_ing.price_per_unit,newRecipeIng.item_mass)
            print(newRecipeIng.calulcate_price())
            data = {
            "mass" : newRecipeIng.item_mass,
            "name" : newRecipeIng.base_ing.ing_name,
            "price" : newRecipeIng.base_ing.price_per_unit(),
            "del_url" : reverse("calculator:ring_delete", kwargs={'id':newRecipeIng.id}),
            "csrf" : get_token(request),
            "obj_id" : newRecipeIng.id,
            "total_price" : newRecipeIng.calulcate_price(),
            "perSprice" : self.get_object().calulcate_price(),
            }

            return JsonResponse(data)

    @staticmethod
    def autocomplete(request):
        query = request.get("term", " ")
        Options = BaseIng.objects.filter(ing_name__icontains=query)
        Options = [option.name for option in Options]

        return JsonResponse(Options)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['ing_list'] = self.get_object().recipeing_set.all()
        context['base_ing'] = BaseIng.objects.all()
        context['servings'] = self.get_object().servings
        context['prices'] = self.get_object().calulcate_price()

        return context

    @csrf_exempt
    @staticmethod
    def delete_ing(request, id):
        Ing = get_object_or_404(RecipeIng, id=id)
        recipe = Ing.recipe
        Ing.delete()
        data = {
            "perSprice" : recipe.calulcate_price(),
            "del" : "Deleted"
        }

        return JsonResponse(data, safe=False)


@method_decorator(csrf_exempt, name='dispatch')
class BaseIngPage(generic.ListView):

    model = BaseIng

    def post(self,request,*args,**kwargs):
        if request.POST.get('ing_name') and request.POST.get('package_price'):
            new_base = BaseIng(ing_name = request.POST.get('ing_name'), package_price = request.POST.get('package_price'), measurement_type=request.POST.get('m_u'), package_size = request.POST.get('package_size'))
            new_base.save()

            return HttpResponseRedirect(reverse("calculator:base_list"))
       
        else:
            Ing = get_object_or_404(BaseIng, id=request.POST.get('id'))
            Ing.delete()
            return JsonResponse("deleted", safe=False)
        

calculator/templates/calculator/baseing_list.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<link href="{% static 'static.css' %}" rel="stylesheet"/>
<script src = '{% static "js/jquery.js" %}'></script>
<script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand animate-charcter" href="#">Recipe Price<br>Calculator</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'calculator:homepage' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'calculator:base_list' %}">Base ingredients</a><span class="sr-only">(current)</span></a>
      </li>
      
    </ul>
  </div>
</nav>

<ul class = "list-group">
{% for ing in object_list %}


<li id = {{ing.id}} class="list-group-item">Ingredent Name: {{ing.ing_name}} Package Price: {{ing.package_price}}  Measurement type: {{ing.measurement_type}} Package Size: {{ing.package_size}} Price per unit: {{ing.price_per_unit}}
  <form action="{% url 'calculator:ing_delete' ing.id %}" method="POST" name="delButton" id="{{ing.id}}">{% csrf_token %}<button class="fill">Delete</button></form></li>

{% endfor %}

</ul>

<br/>
<fieldset>
  <legend><h1>Add a new ingredent</h1></legend>
  <form action="" method="POST">
    {% csrf_token %}
    Ingredent name: <input type="text" name="ing_name" value="">
    Package Price:
    <input type="text" name="package_price" value = "">
    Package Size:
    <input type="text" name="package_size" value = "">
    Measurement type:
    <select name="m_u">
      <option value="mL">mL</option>>
      <option value="L">L</option>>
      <option value="g">g</option>>
      <option value="kg">kg</option>>
      <option value="oz">oz</option>
    </select>
    <input type="submit" value="Post"/>
    </form>
</fieldset>


<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9030501787345966"
     crossorigin="anonymous"></script>
<!-- Ads1 -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9030501787345966"
     data-ad-slot="3854817971"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>

<script>

var delElement = function(event){
  event.preventDefault();
  var self = this;
  $.post($(this).parent().attr("action"), $(this).parent().serialize() + "&id=" + $(this).parent().attr("id"), function(data){
    if(data!=null){
      console.log($(this).parent().serialize())
      $(self).parent().remove();
    }
  });
};

  
  $(document).ready(function(){
    $("[name=delButton]").click(delElement);
  })
  
</script>
  
  

calculator/templates/calculator/homepage.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<link href="{% static 'static.css' %}" rel="stylesheet"/>
<script src = '{% static "js/jquery.js" %}'></script>
<script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand animate-charcter" href="#">Recipe Price<br>Calculator</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'calculator:homepage' %}"><span>Home</span><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'calculator:base_list' %}"><span>Base ingredients</span></a>
      </li>
      
    </ul>
  </div>
</nav>

  <input class ="lookupBar" name="search" id="search">

  <div class = "listElementCont">
    <div class="list-group" id="recipe_list">
      <div href="#" class="list-group-item list-group-item-action" aria-current="true" hidden="true" id="mockEl">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1" name="title"></h5>
          <small name="timestamp">3 days ago</small>
        </div>
        <p class="mb-1" name="desc">Some placeholder content in a paragraph.</p>
        <form action="#" method = "POST" name="form">{% csrf_token %}<button id='delete' name='delete' class='btn btn-danger'>Delete</button></form>
      </div>
      {% for recipe in recipe_list %}
      <div href="{% url 'calculator:ing_list' recipe.id %}" class="list-group-item list-group-item-action" aria-current="true" name="recipeEl">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1" name="title"><a href="{% url 'calculator:ing_list' recipe.id %}">{{recipe.recipe_name}}</a></h5>
          <small name="timestamp">{{recipe.parse_time}}</small>
        </div>
        <p class="mb-1" name="desc">{{recipe.descripton}}</p>
        <form action="{% url 'calculator:recipe_delete' recipe.id %}" method = "POST">{% csrf_token %}<button id='{{recipe.id}}' name='delete' class='btn btn-danger'>Delete</button></form>
      </div>
      {% endfor %}
    </div>
    </div>

    <div name="recipe form" class="recipeForm">
    <h1 class="recipeFormHeading">New Recipe</h1>
<form action="" method="POST" id="recipe_data" name="recipe_adder">
  <div name="recipe_name_form" class="input-group mb-3">
      <span class="input-group-text" id="addon">Recipe name:</span> 
      <input type="text" name="name" value="New recipe" class="form-control">
  </div>
  <div name="recipe_desc" class="input-group mb-3">
    <span class="input-group-text" id="addon">Recipe descripton:</span>
    <textarea name="desc" value="recipe descripton" class="form-control"></textarea>
  </div>
      {% csrf_token %}
    <div name="submit button" class="input-group-mb-3">
      <input type="submit" value="Post" id="submit" class="btn btn-primary">
    </div>
</form>
</div>

<script>

$("#search").on("input", function(){
  $("[name=recipeEl]").remove()
  $.post("search_recipe/", {"name":$("#search").val()}, function(data){
    console.log(data);
    $("#search").autocomplete("option", "source", data)
    refresh(data)
  })
  
  
})

$("#search").autocomplete({source:[], select: function(event, ui){
  event.preventDefault();
  $("#search").val(ui.item.label)
}})

var delElement = function(event){
    event.preventDefault();
    var element = $(this).parent().parent();
    $.post($(this).parent().attr("action"),
    $(this).parent().serialize() + "&id=" + $(this).attr("id"),
    function(data){
      if(data=="Deleted"){
        element.remove();
      }
    });
    console.log($(this).parent().serialize() + "&id=" + $(this).attr("id"));
}
$(document).ready(function(){
  console.log("ready");
$("[name=delete]").click(delElement);
})

let submitbutton = document.getElementById("submit")

var addElement = function(event){
  event.preventDefault();
  console.log($(this).parent().parent().serialize());
  $.post("{% url 'calculator:add_recipe' %}",
  $(this).parent().parent().serialize(),
    function(data){
      if(data!=null){
        let recipe_name = $('[name="name"]').val();
        console.log(data)
        let li = $("#mockEl").clone();
        li.removeAttr("hidden");
        li.find("[name=delete]").click(delElement);
        li.attr("name", "recipeEl")
        li.find("[name=timestamp]").text(data["time"])
        li.find("[name=desc]").text(data["desc"])
        li.find("[name=title]").append('<a href='+data["url"]+' id='+data["id"]+'>'+recipe_name+'</a>');
        li.find("[name=form]").attr("action", data["del_url"]);

        $("#recipe_list").append(li);
        
        console.log(recipe_name);
      }
  })
}
var refresh = function(data){
  for(let i=0;i<data.length; i++){
    if(data[i]!=null){
        let recipe_name = data[i]["label"]
        let li = $("#mockEl").clone();
        li.removeAttr("hidden");
        li.find("[name=delete]").click(delElement);
        li.attr("name", "recipeEl")
        li.find("[name=timestamp]").text(data[i]["date"])
        li.find("[name=desc]").text(data[i]["desc"])
        li.find("[name=title]").append('<a href='+data[i]["url"]+' id='+data[i]["id"]+'>'+recipe_name+'</a>');
        li.find("[name=form]").attr("action", data[i]["del_url"]);

        $("#recipe_list").append(li);
        
      }
  }
    
}



submitbutton.addEventListener("click", addElement);

</script>

calculator/templates/calculator/recipe_detail.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand animate-charcter" href="#">Recipe Price<br>calculator</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>



  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'calculator:homepage' %}">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'calculator:base_list' %}">Base ingrenties</a>
      </li>

    </ul>
    </div>
</nav>



<h1 class="recipeTitle"> {{recipe.recipe_name}} </h1>


<link href="{% static 'recipe_detail.css' %}" rel="stylesheet"/>
<script src = '{% static "js/jquery.js" %}'></script>
<script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<ul id="ing_list" class = "list-group">

{% for ing in ing_list %}
<li id={{ing.id}}><span>{{ing.base_ing.ing_name}} price per unit: {{ing.base_ing.price_per_unit}} Quantity: {{ing.item_mass}} Item price: {{ing.calulcate_price}}</span><form action="{% url 'calculator:ring_delete' ing.id %}" method="POST" id="delete" name="delete">{% csrf_token %}<button class ="button-3" onclick=delElement(event)>Delete</button></form></li>
{% endfor %}
</ul>




<br>
<form action="" method="post">
  {% csrf_token %}
  Serving size:<input type="number" name="servings" value={{servings}}>
 <input type="submit" value="Submit" id="sButton">
</form>

Total recipe price: <span id="total_price">{{prices.0}}</span> Price per serving: <span id="serving_price">{{prices.1}}</span>

<br>
<br>
<form action="" method="POST" id="ing_data">
  {% csrf_token %}
  <input name="ing_name" id=name>
  <input name="ing" id="hiddenIng" hidden="true">
  <input type="text" name="quan" value="" id=quan>
  </select>
  <input type="submit" value="Submit" id="Submit">
</form>




<script>
var foods = []

{% for ing in base_ing %}
foods.push({"label":"{{ing.ing_name}}", "val":{{ing.id}}})
{% endfor %}

$("#name").autocomplete({source:foods, select: function(event, ui){
  $("#name").val(ui.item.label)
  $("#hiddenIng").val(ui.item.val)
}, change : function(event, ui){
  for (var i = 0; i < foods.length; i++) {
  if (foods[i].label == $("#name").val()){
    $("#hiddenIng").val(foods[i].val)
  }
}
}})

let submitbutton = document.getElementById("Submit");


var addItem = function(event){
  event.preventDefault();
  var ingData = new FormData(document.getElementById("ing_data"));
  var name = document.getElementById("name");

  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
      var dict = JSON.parse(xhttp.response);
      var del_button = document.createElement("form")
      var del_button_element = document.createElement("button")

      var ul = document.getElementById("ing_list");
      var li = document.createElement("li");
      li.setAttribute("id", dict["obj_id"]);
      var token = document.createElement("input");

      token.name = "csrfmiddlewaretoken";
      token.value = dict["csrf"];
      token.type = "hidden";

      del_button.method = "POST"
      del_button.action = dict["del_url"];
      del_button_element.innerHTML = "Delete"
      del_button_element.setAttribute("id", dict["obj_id"])
      del_button_element.setAttribute("class", "button-3")
      del_button.appendChild(del_button_element);
      del_button.appendChild(token);
      del_button_element.addEventListener("click", delElement);


      li.innerHTML = dict["name"] + " price per unit: " + dict["price"] + " Quantity: " + dict["mass"] + " Item Price: " + dict["total_price"];

      li.appendChild(del_button);
      ul.appendChild(li);

      $("#serving_price").text(dict["perSprice"][1])
      $("#total_price").text(dict["perSprice"][0])

    }
  };
  xhttp.open("POST", "", true);
  xhttp.send(ingData);
}
submitbutton.addEventListener("click",addItem);

var delElement = function(event){
  event.preventDefault();

  var xhttp = new XMLHttpRequest();
  var button = event.target;
  var form = button.parentElement;
  var rec_id = form.parentElement.id;
  var sendData = new FormData(form);
  sendData.set("id", rec_id);

  xhttp.onreadystatechange = function(){
    if(this.readyState == 4 && this.status == 200){
      var dict = JSON.parse(xhttp.response);
      if(dict["del"] == "Deleted"){
        var li = document.getElementById(rec_id);
        $("#serving_price").text(dict["perSprice"][1]);
        $("#total_price").text(dict["perSprice"][0]);
        li.parentElement.removeChild(li);
      }
    }
  }

  xhttp.open("POST", form.action, true);
  xhttp.send(sendData);
}


var changeServing = function(event){
  event.preventDefault()
  var servingSize = $(this).parent().find("[name=servings]").val();
  console.log(servingSize);
  $.post("", $(this).parent().serialize(), function(data){
    $("#serving_price").text(data["perSprice"][1]);
    $("#total_price").text(data["perSprice"][0])
  })
}

$("#sButton").click(changeServing);





</script>

calculator/templates/calculator/recipe_filter.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}


<link rel="stylesheet" href='{% static "static.css" %}'>
<script src = '{% static "js/jquery.js" %}'></script>
<script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">


<h1 class="tHead">All recipes</h1>

<div name='filters'>
    <div class="btn-group">
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle marginFix" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dateBut">
            Date created
            </button>
            <ul class="dropdown-menu" id="date">
                <li><a class="dropdown-item" href="#">Newest</a></li>
                <li><a class="dropdown-item" href="#">Oldest</a></li>
            </ul>
        </div>
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle marginFix" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="nameBut">
            Name
            </button>
            <ul class="dropdown-menu" id="name">
                <li><a class="dropdown-item" href="#">Ascending</a></li>
                <li><a class="dropdown-item" href="#">Descending</a></li>
            </ul>
        </div>
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle marginFix" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="priceBut">
            Price
            </button>
            <ul class="dropdown-menu", id="price">
                <li><a class="dropdown-item" href="#">Ascending</a></li>
                <li><a class="dropdown-item" href="#">Descending</a></li>
            </ul>
        </div>
    </div>

    <div class="input-group">
        <div class="input-group mb-3 NumIngFilter marginFix" >
            <span class="input-group-text" id="inputGroup-sizing-default">Min Ingrents</span>
            <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" id="minIng">
        </div>
        <div class="input-group mb-3 NumIngFilter marginFix" >
            <span class="input-group-text" id="inputGroup-sizing-default">Max Ingrents</span>
            <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" id="maxIng">
        </div>
    </div>

    <button type="button" class="btn btn-primary" id="applyBut">Apply filters</button>



</div>

<div class="col" id="hidden">
    <div class="card">
      <img src="{% static '051-1.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">recipe.name</h5>
        <p class="card-text">recipe.des</p>
      </div>
    </div>
  </div>

<div class="row row-cols-1 row-cols-md-2 g-4" id = recipeContainer>
    
</div>

<script>
    
    var filters = {"Price": "null", "Name": "null", "Date": "null", "minIng": "null", "maxIng": "null"}

    var populatePage = function(data){
        console.log(data)
        $("#recipeContainer").empty();
        for(var i=0; i<data.length; i++){
            let li = $("#hidden").clone();
            li.find(".card-title").text(data[i].recipe_name);
            li.find(".card-text").text(data[i].descripton);
            li.find(".card-title").wrapInner("<a href=\""+ data[i].url +"\"></a>")
            li.attr("id", "newID");
            $("#recipeContainer").append(li);
        }
    }

    $(document).ready(function(){
        $.post(window.location.href, filters, populatePage);
    });

    $("#name li").click(function(){
        $("#nameBut").text("Name: " + $(this).text());
        filters["Name"] = $(this).text();
    });

    $("#price li").click(function(){
        $("#priceBut").text("Price: " + $(this).text());
        filters["Price"] = $(this).text();
        
    })

    $("#date li").click(function(){
        $("#dateBut").text("Date: " + $(this).text());
        filters["Date"] = $(this).text();
    })

    $("#minIng").change(function(){
        filters["minIng"] = $("#minIng").val();
        console.log(filters["minIng"]);
    })

    $("#maxIng").change(function(){
        filters["maxIng"] = $("#maxIng").val();
        
    })

    

    $("#applyBut").click(function(){
        $.post(window.location.href, filters, populatePage);
    })

</script>